config:
  config:
    akeneoreferenceentity/application/configuration/attribute:
      flagbit_table:
        icon: bundles/pimui/images/attribute/icon-multiselect.svg
        denormalize: '@flagbitreferenceentitytable/reference-entity/attribute/table/table.ts'
        reducer: '@flagbitreferenceentitytable/reference-entity/attribute/table/reducer.ts'
        view: '@flagbitreferenceentitytable/reference-entity/attribute/table/view.tsx'
